@startuml bridge_pattern

!define DARKORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

abstract class Abstraction <<Window>>{
    - Implementor impl;
    + {abstract} function();
}

class RefinedAbstraction {
    + function();
}

abstract class Implementor <<View>>{
    + {abstract} implementation();
}

class ConcreateImplementor {
    + implementation();
}

Abstraction <|-- RefinedAbstraction
Implementor <|-- ConcreateImplementor
Abstraction o-right- Implementor

note "LongWindow and ShortWindow" as N1
N1 .up. RefinedAbstraction
note "MusicAlbumView and BookView" as N2
N2 .up. ConcreateImplementor

@enduml