@startuml iterator

!define DARKORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

abstract class IterableCollection <<SongsCollection>> {
    + {abstract} create_iterator();
}

abstract class Iterator <<Iterator>> {
    + {abstract} has_next();
    + {abstract} next();
}

class ConcreateCollection <<SongsOf80s, SongsOf90s>>{
    + create_iterator();
}

class ConcreateIterator <<StaticArrayIterator, DynamicArrayIterator>>{
    + has_next();
    + next();
}


allow_mixing
rectangle Client #DarkOliveGreen
Client --> IterableCollection
Client --> Iterator

IterableCollection <|-- ConcreateCollection
Iterator <|-- ConcreateIterator
ConcreateCollection .left.> ConcreateIterator : <<create>>
ConcreateCollection <-- ConcreateIterator
@enduml